#EX2
array1 = [7,5,10,14,3,9,7]
array2 = [9,10,3,4,2,5,7,1]
print("Find length and print both arrays Array 1: ",len(array1))
print("Find length and print both arrays Array 2: ",len(array2))
array1.insert(8, 15)
print("Inserted array1 = : ",array1)
index1 = array1.index(7)
index2 = array2.index(7)
print("Find index of 7 in 2 arrays Array 1 : ",index1)
print("Find index of 7 in 2 arrays Array 2 : ",index2)
print("Append 1 in first array and 14 in second array")
array1.append(1)
array2.append(14)
print("Array 1 = ",array1)
print("Array 2 = ",array2)
print("Copy 1stArray to create new array (3rdArray)")
array3 = array1.copy()
print("Array 3 copy = ",array3)
print("Merge new array and 2ndArray together (3rdArray and 2ndArray)")
array2.extend(array3)
print("Merged Array 2 = ",array2)
index3 = array2.index(7)
print("Count value of 7 in 3rdArray = ",index3)
print("Sort 3rdArray")
array3.sort()
print("3rdArray = ",array3)
print("Remove 7 in 3rdArray")
array3.remove(7)
array3.remove(7)
print(array3)
print("Copy 3rdArray to 4thArray")
array4 = array3.copy()
print(array4)
print("Reverse 4thArray")
array4.reverse()
print(array4)
print("array 3 = ",array3)
print("array 4 = ",array4)